ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.vardevops.online
REDIS_HOST: redis-dev.vardevops.online
USER_HOST: user-dev.vardevops.online
CATALOGUE_HOST: catalogue-dev.vardevops.online
CART_HOST: cart-dev.vardevops.online
MYSQL_HOST: mysql-dev.vardevops.online
SHIPPING_HOST: shipping-dev.vardevops.online
PAYMENT_HOST: payment-dev.vardevops.online
RABBITMQ_HOST: rabbitmq-dev.vardevops.online