# Day 29

- name: message 1
  ansible.builtin.debug:
    msg: "Hi from message 1"


- name: message 2
  ansible.builtin.debug:
    msg: "Hi from message 2"



- name: message 3
  ansible.builtin.debug:
    msg: "Hi from message 3"
